pin "application"
pin "sfx"
pin "pixi_shatter"
pin "pixi.js", to: "https://cdn.jsdelivr.net/npm/pixi.js@7.4.3/dist/pixi.min.mjs"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "@rails/actioncable", to: "actioncable.esm.js"
pin_all_from "app/javascript/channels", under: "channels"
